string LINEAR_SVM = 'lsvm'
string RADIAL_SVM = 'rsvm'
string GRID_SEARCH_SVM = 'gssvm'
string GAUSSIAN_MIXTURE_MODELS = 'gmm'
string DECISION_TREE = 'dt'
string GAUSSIAN_NAIVE_BAYES = 'gnb'
string K_NEAREST_NEIGHBORS = 'knn'
string classifier_type
string classifier_name
---
bool sucess