subscribers:
  
  queue_size: 5

  image_rgb:
    topic: /kinect2/rgb/image_raw

  image_depth:
    topic: /kinect2/depth/image_raw

  camera_info:
    topic: /kinect2/rgb/camera_info

  points:
    topic: /kinect2/depth/points

publishers:
  
  queue_size: 1

  image_rgb:
    topic: /butia_vision/bvb/image_rgb_raw

  image_depth:
    topic: /butia_vision/bvb/image_depth_raw

  camera_info:
    topic: /butia_vision/bvb/camera_info

  points:
    topic: /butia_vision/bvb/points

servers:

  image_request:
    service: /butia_vision/bvb/image_request
