subscribers:
  
  queue_size: 50

  image_rgb:
    topic: /kinect2/rgb/image_raw

  image_depth:
    topic: /kinect2/depth/image_raw
  
  points:
    topic: /kinect2/depth/points

  camera_info:
    topic: /kinect2/rgb/camera_info

server:

  image_request:
    service: /butia_vision/is/image_request

parameters:
  buffer_size: 150
  use_exact_time: true