subscribers:
  
  queue_size: 5

  image_rgb:
    topic: /vision_system/vsb/image_rgb_raw

  image_depth:
    topic: /vision_system/vsb/image_depth_raw

  camera_info:
    topic: /vision_system/vsb/camera_info

server:

  image_request:
    service: /vision_system/is/image_request

parameters:
  buffer_size: 150
  use_exact_time: true