services:
  people_tracking:
    start_tracking: "/butia_vision/pt/start"
    stop_tracking: "/butia_vision/pt/stop"
    
topics:
  butia_recognition:
    people_detection: "/butia_vision/br/people_detection"
  people_tracking:
    people_tracking: "/butia_vision/pt/people_tracking"