threshold: 0.5

subscribers:
  
  queue_size: 100
  exact_time: false
  slop: 0.5

<<<<<<< HEAD
  image_rgb: /butia_vision/bvb/image_rgb

  #points: /butia_vision/bvb/points
=======
  #points: kinect2/qhd/points
  image_rgb: /butia_vision/bvb/image_rgb
  camera_info: /butia_vision/bvb/camera_info
  image_depth: /butia_vision/bvb/image_depth
>>>>>>> 072dcfb1511b7da47ffff08740a94af16dd5a471

publishers:

  face_recognition:
    topic: /butia_vision/br/face_recognition
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/people_detection/list_classes

  start:
    service: /butia_vision/br/people_detection/start

  stop:
    service: /butia_vision/br/people_detection/stop

names:
    starting: features
