threshold: 0.5
use_ram: false
use_sam: true
box_threshold: 0.6

classes: [bottle]
max_sizes:
    - [0.5, 0.5, 0.5]

subscribers:
  
  queue_size: 1
  exact_time: true
  slop: 0.5

  image_rgb: /butia_vision/bvb/image_rgb
  camera_info: /butia_vision/bvb/camera_info
  image_depth: /butia_vision/bvb/image_depth

  #points: /butia_vision/bvb/points
  #points: kinect2/qhd/points

publishers:

  face_recognition:
    topic: /butia_vision/br/face_recognition
    queue_size: 1
  debug:
    topic: /butia_vision/br/debug_face
    queue_size: 1
servers:

  list_classes:
    service: /butia_vision/br/people_detection/list_classes

  start:
    service: /butia_vision/br/people_detection/start

  stop:
    service: /butia_vision/br/people_detection/stop

names:
    starting: features
