use_ram: false
use_sam: true
box_threshold: 0.6

classes: [bottle]
max_sizes:
    - [0.5, 0.5, 0.5]

subscribers:
  
  queue_size: 1
  exact_time: false
  slop: 0.2

  image_rgb: /camera/rgb/image_color
  #image_rgb: /image_publisher/image_raw

  #points: /butia_vision/bvb/points
  
  image_depth: /camera/depth/image

  camera_info: /camera/rgb/camera_info
  #camera_info: /image_publisher/camera_info

publishers:

  object_recognition:
    topic: /butia_vision/br/object_recognition
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/object_recognition/list_classes

  start:
    service: /butia_vision/br/object_recognition/start

  stop:
    service: /butia_vision/br/object_recognition/stop
