threshold: 0.3
classes_by_category:
    people: [person]
    coco: [bicycle, car, motorcycle, airplane, bus, train, truck, boat, traffic light,
        fire hydrant, stop sign, parking meter, bench, bird, cat, dog, horse, sheep, cow,
        elephant, bear, zebra, giraffe, backpack, umbrella, handbag, tie, suitcase, frisbee,
        skis, snowboard, sports ball, kite, baseball bat, baseball glove, skateboard, surfboard,
        tennis racket, bottle, wine glass, cup, fork, knife, spoon, bowl, banana, apple,
        sandwich, orange, broccoli, carrot, hot dog, pizza, donut, cake, chair, couch,
        potted plant, bed, dining table, toilet, tv, laptop, mouse, remote, keyboard, cell phone,
        microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors, teddy bear,
        hair drier, toothbrush]
all_classes:
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - truck
    - boat
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcase
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
    - tv
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
model_file: yolov8n.pt

max_sizes:
    - [0.5, 2.5, 0.5]

model_file: yolov8_lab_objects.pt

subscribers:
  
  queue_size: 1
  exact_time: false
  slop: 0.2

  # image_rgb: /butia_vision/bvb/image_rgb
  # camera_info: /butia_vision/bvb/camera_info
  # image_depth: /butia_vision/bvb/image_depth
  #points: /butia_vision/bvb/points

  image_rgb: /camera/rgb/image_raw
  camera_info: /camera/rgb/camera_info
  image_depth: /camera/depth/image_raw

publishers:

  object_recognition:
    topic: /butia_vision/br/object_recognition
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/object_recognition/list_classes

  start:
    service: /butia_vision/br/object_recognition/start

  stop:
    service: /butia_vision/br/object_recognition/stop
