threshold: 0.3
classes_by_category:
    Drinks: ['cola', 'fanta', 'dubbelfris', 'water', 'ice_tea', 'big_coke', 'milk']
    Cleaning_supplies: ['sponges', 'soap', 'dishwasher_tab', 'washcloth']
    Decorations: ['candle']
    Dishes: ['plate', 'bowl', 'cup', 'fork', 'knife', 'spoon']
    Food: ['cornflakes', 'pancake_mix', 'mayonaise', 'sausages', 'pea_soup', 'curry', 'hagelslag']
    Snacks: ['candy', 'liquorice', 'pringles', 'tictac', 'stroopwafel', 'crisps']
    Fruits: ['lemon']

all_classes:
  - 'big_coke'
  - 'bowl'
  - 'candle'
  - 'candy'
  - 'cola'
  - 'cornflakes'
  - 'crisps'
  - 'cup'
  - 'curry'
  - 'dishwasher_tab'
  - 'dubbelfris'
  - 'fanta'
  - 'fork'
  - 'hagelslag'
  - 'ice_tea'
  - 'knife'
  - 'lemon'
  - 'liquorice'
  - 'mayonaise'
  - 'milk'
  - 'pancake_mix'
  - 'pea_soup'
  - 'plate'
  - 'pringles'
  - 'sausages'
  - 'soap'
  - 'sponges'
  - 'spoon'
  - 'stroopwafel'
  - 'tictac'
  - 'washcloth'
  - 'water'
  
max_sizes:
    - [0.05, 0.05, 0.05]

model_file: robocup_2024_v1_small.pt

subscribers:
  
  queue_size: 1
  exact_time: false
  slop: 0.2

  image_rgb: /butia_vision/bvb/image_rgb
  camera_info: /butia_vision/bvb/camera_info
  image_depth: /butia_vision/bvb/image_depth
  
publishers:

  object_recognition:
    topic: /butia_vision/br/object_recognition
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/object_recognition/list_classes

  start:
    service: /butia_vision/br/object_recognition/start

  stop:
    service: /butia_vision/br/object_recognition/stop
