threshold: 0.8
classes_by_category:
    drink: ['guarana', 'Guarana', 'IceTea', 'tonic', Tonic', 'Coke', 'Beer can', 'CoconutWater', 'Water', Soda can']
    snack: ['corn flakes', 'CornFlakes', 'pringles', 'Pringles', 'Popcorn', 'Cookies', 'Cracker', 'Chocolate Milk', 'TunaCan']
    fruits: ['apple', 'Apple', 'kiwi', 'Kiwi', 'orange', 'Banana', 'Orange']
    cutlelary: ['bowl', 'Bowl', 'fork', 'knife', 'plate', 'Plate', 'Cleaner', 'Napkin', 'Cloth', 'EnglishSauce', 'TomatoSauce']
    misc: ['sponge', 'Sponge', 'Bag', 'Alcohol Bottle', 'Soap', 'Mug', 'Carrot', 'Yeast', 'Coconut Milk', 'Chocolate Powder', 'Ketchup', 'Mayonnaise', 'Mustard', 'Toothpaste', 'Gelatine']
all_classes: 
    - Alcohol Bottle
    - Apple
    - Bag
    - Banana
    - Beer can
    - Bowl
    - Carrot
    - Chocolate Milk
    - Chocolate Powder
    - Cleaner
    - Cloth
    - Coconut Milk
    - CoconutWater
    - Coke
    - Cookies
    - CornFlakes
    - Cracker
    - EnglishSauce
    - Gelatine
    - Guarana
    - IceTea
    - Ketchup
    - Kiwi
    - Mayonnaise
    - Mug
    - Mustard
    - Napkin
    - Orange
    - Plate
    - Popcorn
    - Pringles
    - Soap
    - Soda can
    - Sponge
    - TomatoSauce
    - Tonic
    - Toothpaste
    - TunaCan
    - Water
    - Yeast
    - apple
    - bowl
    - corn flakes
    - fork
    - guarana
    - kiwi
    - knife
    - orange
    - plate
    - pringles
    - sponge
    - tonic
  
max_sizes:
    - [0.5, 2.5, 0.5]

model_file: yolov8_lab_objects.pt

subscribers:
  
  queue_size: 1
  exact_time: false
  slop: 0.2

  # image_rgb: /butia_vision/bvb/image_rgb
  # camera_info: /butia_vision/bvb/camera_info
  # image_depth: /butia_vision/bvb/image_depth
  #points: /butia_vision/bvb/points

  image_rgb: /camera/color/image_raw
  camera_info: /camera/color/camera_info
  image_depth: /camera/aligned_depth_to_color/image_raw

publishers:

  object_recognition:
    topic: /butia_vision/br/object_recognition
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/object_recognition/list_classes

  start:
    service: /butia_vision/br/object_recognition/start

  stop:
    service: /butia_vision/br/object_recognition/stop
