threshold: 0.3
classes_by_category:
    Drinks: ['nescau', 'kuat', 'cononut water', 'fanta']
    Cleaning supplies: ['detergent', 'sponge', 'cloth']
    Pantry items: ['gelatin', 'mustard', 'shoyo', 'sauce', 'tea']
    Fruits: ['apple', 'pear', 'tangerine']
    Snacks: ['treloso', 'chocolate', 'peanut']

all_classes:
  - 'apple'
  - 'chocolate'
  - 'cloth'
  - 'cononut water'
  - 'detergent'
  - 'fanta'
  - 'gelatin'
  - 'kuat'
  - 'mustard'
  - 'nescau'
  - 'peanut'
  - 'pear'
  - 'sauce'
  - 'shoyo'
  - 'sponge'
  - 'tangerine'
  - 'tea'
  - 'treloso'
  
max_sizes:
    - [0.05, 0.05, 0.05]

model_file: larc2023_best_yolov8.pt

subscribers:
  
  queue_size: 1
  exact_time: false
  slop: 0.2

  image_rgb: /butia_vision/bvb/image_rgb
  camera_info: /butia_vision/bvb/camera_info
  image_depth: /butia_vision/bvb/image_depth
  
publishers:

  object_recognition:
    topic: /butia_vision/br/object_recognition
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/object_recognition/list_classes

  start:
    service: /butia_vision/br/object_recognition/start

  stop:
    service: /butia_vision/br/object_recognition/stop
