debug_kpt_threshold: 0.5

classes_by_category:
    people: [person]
classes:
    - person

model_file: yolov8s-pose.pt
reid_model_file: osnet_x0_25_msmt17.pt

subscribers:
  
  queue_size: 1
  exact_time: false
  slop: 0.5

  image_rgb: /butia_vision/bvb/image_rgb

  image_depth: /butia_vision/bvb/image_depth

  camera_info: /butia_vision/bvb/camera_info


publishers:

  recognition:
    topic: /butia_vision/br/recognition
    queue_size: 1
    
  debug:
    topic: /butia_vision/br/debug
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/yolo_tracking/list_classes

  start:
    service: /butia_vision/br/yolo_tracking/start

  stop:
    service: /butia_vision/br/yolo_tracking/stop

services:
  tracking:
    start: /butia_vision/pt/start
    stop: /butia_vision/pt/stop

tracking:
  start_on_init: false
  thresholds:
    reid_threshold: 0.3
    iou_threshold: 0.15
    max_age: 5
