threshold: 0.5
reid_threshold: 0.3
classes_by_category:
    people: [person]
classes:
    - person

model_file: yolov8s-pose.pt
reid_model_file: osnet_x0_25_msmt17.pt

subscribers:
  
  queue_size: 1
  exact_time: false
  slop: 0.2

  image_rgb: /kinect2/qhd/image_color_rect

  points: /kinect2/qhd/points

publishers:

  pose_recognition:
    topic: /butia_vision/br/pose_recognition
    queue_size: 1

servers:

  list_classes:
    service: /butia_vision/br/pose_recognition/list_classes

  start:
    service: /butia_vision/br/pose_recognition/start

  stop:
    service: /butia_vision/br/pose_recognition/stop
