name: "Build Docker Image"
on:
  repository_dispatch:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build_registry_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add apt nvidia repository
        run: |
          curl https://get.docker.com | sh \
          && sudo systemctl --now enable docker \
          && distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
          && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
          && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install nvidia-docker2 nvidia-driver-470 && sudo systemctl stop docker && nvidia-smi
      - name: Add nvidia runtime
        run: |
          sudo dockerd --add-runtime nvidia=/usr/bin/nvidia-container-runtime --default-runtime=nvidia &
      - name: Init and update submodules
        run: |
          git submodule init && git submodule update
      - name: Build images
        run: |
          ./build.sh
      - name: Log into registry
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push images
        run: |
          ./push.sh   