name: "Build Docker Image"
on:
  repository_dispatch:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build_registry_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Init and update submodules
        run: |
        git submodule init && git submodule update
      - name: Build images
        run: |
          ./build.sh
      - name: Log into registry
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push images
        run: |
          ./push.sh   